# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160514_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'site icon', 'verbose_name_plural': 'site icons'},
        ),
        migrations.AlterModelOptions(
            name='pony',
            options={'verbose_name': 'pony icon', 'verbose_name_plural': 'pony icons'},
        ),
    ]
