# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:19
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161023_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='userurl',
            name='url',
            field=users.models.UrlField(max_length=200),
        ),
    ]
