version: "2"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginx:/etc/nginx/conf.d/
            - app:/srv/app/data
        networks:
            - front
    django:
        build:
            context: .
            dockerfile: docker/python-prod
        command: ./deploy.sh
        volumes:
            - app:/srv/app/data
        links:
            - redis
            - postgres
        environment:
            - DEPLOY_TYPE=prod
        ports: []
    celery:
        build:
            context: .
            dockerfile: docker/python-prod
        environment:
            - DEPLOY_TYPE=prod
        volumes:
            - app:/srv/app/data

volumes:
    nginx: ~
