postgre:
    image: postgres:9.4
    restart: always
redis:
    image: redis:3.0
    restart: always
django:
    build: .
    dockerfile: docker/python-prod
    command: uwsgi --emperor '/uwsgi/instances/*/uwsgi.ini' --nagios
    volumes:
        - .:/srv/app
    ports:
        - "8000:80"
    links:
        - redis
        - postgre
    restart: always
#celery:
#    build: .
#    dockerfile: docker/python-prod
#    command: celery -A sugarcub worker -l info
#    volumes:
#        - .:/srv/app
#    links:
#        - redis
#        - postgre
#    restart: always
#mailman:
#    build: .
#    dockerfile: docker/mailman
#    command: ./bin/mailman-web-django-admin runserver 0.0.0.0:8000
#    links:
#        - redis
#        - postgre
#    restart: always
