version: "2"

services:

    nginx:
        #image: mdevlamynck/sugarcub_nginx:${COMPOSE_PROJECT_NAME}_${GIT_COMMIT_ID}
        build:
            context: .
            dockerfile: docker/nginx
        restart: always
        volumes:
            - app_data:/srv/app/data
        networks:
            - front
            - proxy
        environment:
            - VIRTUAL_HOST=sugarcub.bronycub.org
            - VIRTUAL_PORT=80

    django:
        #image: mdevlamynck/sugarcub_django:${COMPOSE_PROJECT_NAME}_${GIT_COMMIT_ID}
        build:
            context: .
            dockerfile: docker/python-prod
        command: bash -c 'docker/run.sh'
        environment:
            - DEPLOY_TYPE=prod
            - ALLOWED_HOSTS=sugarcub.bronycub.org

    celery:
        # Switch to the image without the tests dependencies
        #image: mdevlamynck/sugarcub_django:${COMPOSE_PROJECT_NAME}_${GIT_COMMIT_ID}
        build:
            context: .
            dockerfile: docker/python-prod
        environment:
            - DEPLOY_TYPE=prod
            - ALLOWED_HOSTS=sugarcub.bronycub.org

networks:
    proxy:
        external:
            name: proxy
