# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 12:57
from __future__             import unicode_literals
from django.core.management import call_command
from django.db              import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160514_1601'),
    ]

    operations = [
    ]
