FROM sugarcub-base
MAINTAINER matthias.devlamynck@mailoo.org

RUN apt-get install -y     \
		gettext            \
		memcached          \
		python3            \
		python3-dev        \
		python3-pip        \
		python-virtualenv  \
		sqlite
